import 'dart:math';
import 'package:uuid/uuid.dart';
import '../models/trading_card.dart';

class PackService {
  final _uuid = const Uuid();
  final _random = Random();

  List<TradingCard> openPack() {
    return List.generate(5, (_) => _generateRandomCard());
  }

  TradingCard _generateRandomCard() {
    final rarity = _rollRarity();
    final stats = _generateStats(rarity);

    return TradingCard(
      id: _uuid.v4(),
      name: _generateName(rarity),
      rarity: rarity,
      imageUrl:
          'assets/cards/placeholder.png', // We'll use a placeholder or generate one
      stats: stats,
      description: "A unique digital collectible generated by AI.",
    );
  }

  CardRarity _rollRarity() {
    final roll = _random.nextDouble();
    if (roll < 0.01) return CardRarity.cyber; // 1%
    if (roll < 0.05) return CardRarity.legendary; // 4%
    if (roll < 0.15) return CardRarity.epic; // 10%
    if (roll < 0.40) return CardRarity.rare; // 25%
    return CardRarity.common; // 60%
  }

  Map<String, int> _generateStats(CardRarity rarity) {
    int baseStat = 50;
    switch (rarity) {
      case CardRarity.common:
        baseStat = 60;
        break;
      case CardRarity.rare:
        baseStat = 70;
        break;
      case CardRarity.epic:
        baseStat = 80;
        break;
      case CardRarity.legendary:
        baseStat = 90;
        break;
      case CardRarity.cyber:
        baseStat = 95;
        break;
    }

    return {
      'PACE': (baseStat + _random.nextInt(10)).clamp(0, 99),
      'SHOOT': (baseStat + _random.nextInt(10)).clamp(0, 99),
      'PASS': (baseStat + _random.nextInt(10)).clamp(0, 99),
      'DRIBBLE': (baseStat + _random.nextInt(10)).clamp(0, 99),
      'DEFENSE': (baseStat + _random.nextInt(10)).clamp(0, 99),
      'PHYSICAL': (baseStat + _random.nextInt(10)).clamp(0, 99),
    };
  }

  String _generateName(CardRarity rarity) {
    final prefixes = [
      'Neon',
      'Cyber',
      'Void',
      'Quantum',
      'Plasma',
      'Mecha',
      'Neural',
      'Glitch',
    ];
    final suffixes = [
      'Striker',
      'Keeper',
      'Defender',
      'Wing',
      'Engine',
      'Ghost',
      'Titan',
      'Viper',
    ];

    return "${prefixes[_random.nextInt(prefixes.length)]} ${suffixes[_random.nextInt(suffixes.length)]}";
  }
}
